# Inspired by https://docs.docker.com/compose/django/
version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./docker-init-db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - db:/var/lib/postgresql/data

  redis:
    image: redis:6

  web:
    image: openformulieren/open-forms:latest
    environment:
      - DJANGO_SETTINGS_MODULE=openforms.conf.docker
      - SECRET_KEY=${SECRET_KEY:-7617hlqsd_u&cuwzm_2ap*^68@dt9hu%n*p9b0u$=q43-fs7ge}
      - DB_NAME=openforms
      - DB_USER=openforms
      - DB_HOST=db
      - CACHE_DEFAULT=redis:6379/0
      - CACHE_AXES=redis:6379/0
      - ALLOWED_HOSTS=*
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  db:
