blank_issues_enabled: true
contact_links:
- name: Report a security vulnerability
    url: https://github.com/open-formulieren/open-forms/security/policy
    about: Please review our security policy for more details
- name: Priority support
    url: https://opengem.nl
    about: Contact us directly to get priority support.
